name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
    paths:
    - 'terms/**'
    - 'captions/**'

jobs:
  notify-before:
    runs-on: ubuntu-latest
    steps:
      - uses: CamiloGarciaLaRotta/watermelon-http-client@v1.4
        with:
          url: https://notificationsendpoint.azurewebsites.net/api/send
          method: post
          headers: '{ "x-functions-key": "${{ secrets.NotifyFunctionKey }}" }'
          data:  '{	"title": "Copying Markdown and caption files", "body": "Ready to copy Markdown and caption files to Azure", "channel": "MSGlossary" }'
  upload-captions:
    runs-on: ubuntu-latest
    needs: notify-before
    steps:
      - uses: actions/checkout@master
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: 'captions'
          container_name: 'captions'
          connection_string: ${{ secrets.StorageConnectionString }}
  upload-markdown:
    runs-on: ubuntu-latest
    needs: upload-captions
    steps:
      - uses: actions/checkout@master
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: 'terms'
          container_name: 'terms'
          connection_string: ${{ secrets.StorageConnectionString }}
  trigger-update:
    runs-on: ubuntu-latest
    needs: upload-markdown
    steps:
      - uses: CamiloGarciaLaRotta/watermelon-http-client@v1.4
        with:
          url: https://msglossary-app.azurewebsites.net/api/update-docs
          method: get
          headers: '{ "x-functions-key": "${{ secrets.UpdateFunctionKey }}" }'
  notify-after:
    runs-on: ubuntu-latest
    needs: trigger-update
    steps:
      - uses: CamiloGarciaLaRotta/watermelon-http-client@v1.4
        with:
          url: https://notificationsendpoint.azurewebsites.net/api/send
          method: post
          headers: '{ "x-functions-key": "${{ secrets.NotifyFunctionKey }}" }'
          data:  '{	"title": "Markdown and caption files copied", "body": "Markdown and caption files were copied to the markdown folder, update process was triggered", "channel": "MSGlossary" }'
